### ISSUE TITLE
[BUG] - Clear Cache produces an error

### ISSUE THREAD

**Issue by avant-guvnor** [Nigel1992/plugin.video.iptvxc#3]
### Short description

Selecting Extras > Clear Cache produces an error

### Steps to reproduce

1. Open addon
2. Select Extras
3. Select Clear Cache
4. An error occurs

### Expected behavior

I expect the cache to be cleared without an error.

### Observed behavior

XCUI Streams error
Check the log for more information.

### Kodi Version (Omega 21.x)

Other

### Device

PC

### Device OS

Windows 10 Pro 22H2

### Troubleshooting steps tried

From the Kodi.log:

 info <general>: plugin.video.iptvxc: Addon file cache cleared (0 files)
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'AttributeError'>
                 Error Contents: module 'xbmc' has no attribute 'translatePath'
                 Traceback (most recent call last):
                   File "C:\Users\%username%\Kodi\portable_data\addons\plugin.video.iptvxc\default.py", line 1310, in <module>
                     addonsettings(url,description)
                   File "C:\Users\%username%\Kodi\portable_data\addons\plugin.video.iptvxc\default.py", line 754, in addonsettings
                     tools.clear_cache()
                   File "C:\Users\%username%\Kodi\portable_data\addons\plugin.video.iptvxc\resources\modules\tools.py", line 468, in clear_cache
                     xbmc_cache_path = os.path.join(xbmc.translatePath('special://home'), 'cache')
                 AttributeError: module 'xbmc' has no attribute 'translatePath'
                 -->End of Python script error report<--

### Logs / additional information

Kodi 21.3 portable install
Addon version 3.8.6

**Comment by Nigel1992** [comment]
Hi @avant-guvnor — this should now be fixed in [XCUI Streams v3.8.7](https://github.com/Nigel1992/plugin.video.iptvxc/releases/tag/v3.8.7).

The error was caused by Kodi 21 no longer providing `xbmc.translatePath()`. Clear Cache now uses Kodi's supported cross-platform `xbmcvfs.translatePath()` API instead.

Please install the `plugin.video.iptvxc-3.8.7.zip` asset from the release, retry **Extras → Clear Cache** on your Windows 10 / Kodi 21.3 setup, and let me know whether it now completes without an error. I'll leave this issue open pending your confirmation.

**Comment by avant-guvnor** [comment]
Hi @Nigel1992 

I can confirm that Clear Cache is now working on my Windows 10 / Kodi 21.3 setup. Many thanks.

**Comment by Nigel1992** [comment]
No problem!
